spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
  application: 
    name: microservicecloud-config-zrf-dev
    
---

spring:
  profiles: test1
  application:
    name: microservicecloud-config-zrf-test1